In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('CF-Insider-Trading-equities-14-09-2022-to-14-09-2023.csv')

In [3]:
df.head().T

,0,1,2,3,4
SYMBOL_\n,NSIL,NSIL,WESTLIFE,WESTLIFE,TIRUPATI
COMPANY_\n,Nalwa Sons Investments Limited,Nalwa Sons Investments Limited,WESTLIFE FOODWORLD LIMITED,WESTLIFE FOODWORLD LIMITED,Shree Tirupati Balajee FIBC Limited
REGULATION_\n,7(2),7(2),7(2),7(2),7(2)
NAME_OF_THE_ACQUIRER/DISPOSER_\n,ARTI JINDAL,PRJ FAMILY MANAGEMENT CO PVT LTD TRUSTEE FOR P...,Banwari Lal Jatia,Banwari Lal Jatia jointly with Ushadevi Jatia,Binod Kumar Agarwal
CATEGORY_OF_PERSON_\n,Promoter Group,Promoter Group,Promoter Group,Promoter Group,Promoters
TYPE_OF_SECURITY_(PRIOR)_\n,Equity Shares,Equity Shares,Equity Shares,Equity Shares,Equity Shares
NO._OF_SECURITY_(PRIOR)_\n,2479,Nil,50,1187,240628
%_SHAREHOLDING_(PRIOR)_\n,0.05,0.0,0.0,0.0,2.37
TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED)_\n,NaN,NaN,NaN,NaN,NaN
NO._OF_SECURITIES_(ACQUIRED/DISPLOSED)_\n,2469.0,2469.0,50.0,50.0,876.0
VALUE_OF_SECURITY_(ACQUIRED/DISPLOSED)_\n,0,0,0,0,176076
ACQUISITION/DISPOSAL_TRANSACTION_TYPE_\n,Sell,Buy,Sell,Buy,Buy
TYPE_OF_SECURITY_(POST)_\n,Equity Shares,Equity Shares,Equity Shares,Equity Shares,Equity Shares
NO._OF_SECURITY_(POST)_\n,10,2469,Nil,1237,241504
%_POST_\n,0,0.05,0,0,2.38
DATE_OF_ALLOTMENT/___ACQUISITION_FROM_\n,12-Sep-23,12-Sep-23,12-Sep-23,12-Sep-23,12-Sep-23
Unnamed: 16,09-Jan-00,NaN,NaN,NaN,NaN
DATE OF ALLOTMENT/ ACQUISITION TO \n,12-Sep-23,12-Sep-23,12-Sep-23,12-Sep-23,14-Sep-23
DATE OF INITMATION TO COMPANY \n,13-Sep-23,13-Sep-23,13-Sep-23,13-Sep-23,14-Sep-23
MODE OF ACQUISITION \n,Gift,Gift,Inter-se-Transfer,Inter-se-Transfer,Off Market
DERIVATIVE TYPE SECURITY \n,-,-,-,-,-
DERIVATIVE CONTRACT SPECIFICATION \n,-,-,-,-,-
NOTIONAL VALUE(BUY) \n,0.0,0.0,0.0,0.0,0.0
NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n,0,0,0,0,0
NOTIONAL VALUE(SELL) \n,0.0,0.0,0.0,0.0,0.0
NUMBER OF UNITS/CONTRACT LOT SIZE (SELL) \n,0,0,0,0,0
EXCHANGE \n,NaN,NaN,NaN,NaN,NSE
REMARK \n,-,-,-,-,-
BROADCASTE DATE AND TIME \n,14-09-2023 13:37,14-09-2023 13:37,14-09-2023 13:19,14-09-2023 13:19,14-09-2023 13:07
XBRL \n,https://archives.nseindia.com/corporate/xbrl/I...,https://archives.nseindia.com/corporate/xbrl/I...,https://archives.nseindia.com/corporate/xbrl/I...,https://archives.nseindia.com/corporate/xbrl/I...,https://archives.nseindia.com/corporate/xbrl/I...

In [4]:
df['COMPANY_\n'].unique

<bound method Series.unique of 0             Nalwa Sons Investments Limited
1             Nalwa Sons Investments Limited
2                 WESTLIFE FOODWORLD LIMITED
3                 WESTLIFE FOODWORLD LIMITED
4        Shree Tirupati Balajee FIBC Limited
                        ...
18237              Mahalaxmi Rubtech Limited
18238              Mahalaxmi Rubtech Limited
18239                eClerx Services Limited
18240                eClerx Services Limited
18241    Madhya Bharat Agro Products Limited
Name: COMPANY_\n, Length: 18242, dtype: object>

In [5]:
a=pd.Series(df.columns)
b=a.str.replace('_\n','')
df.columns=b
df

,SYMBOL,COMPANY,REGULATION,NAME_OF_THE_ACQUIRER/DISPOSER,CATEGORY_OF_PERSON,TYPE_OF_SECURITY_(PRIOR),NO._OF_SECURITY_(PRIOR),%_SHAREHOLDING_(PRIOR),TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED),NO._OF_SECURITIES_(ACQUIRED/DISPLOSED),...,DERIVATIVE TYPE SECURITY \n,DERIVATIVE CONTRACT SPECIFICATION \n,NOTIONAL VALUE(BUY) \n,NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n,NOTIONAL VALUE(SELL) \n,NUMBER OF UNITS/CONTRACT LOT SIZE (SELL) \n,EXCHANGE \n,REMARK \n,BROADCASTE DATE AND TIME \n,XBRL \n
0,NSIL,Nalwa Sons Investments Limited,7(2),ARTI JINDAL,Promoter Group,Equity Shares,2479,0.05,NaN,2469.0,...,-,-,0.0,0,0.0,0,NaN,-,14-09-2023 13:37,https://archives.nseindia.com/corporate/xbrl/I...
1,NSIL,Nalwa Sons Investments Limited,7(2),PRJ FAMILY MANAGEMENT CO PVT LTD TRUSTEE FOR P...,Promoter Group,Equity Shares,Nil,0.00,NaN,2469.0,...,-,-,0.0,0,0.0,0,NaN,-,14-09-2023 13:37,https://archives.nseindia.com/corporate/xbrl/I...
2,WESTLIFE,WESTLIFE FOODWORLD LIMITED,7(2),Banwari Lal Jatia,Promoter Group,Equity Shares,50,0.00,NaN,50.0,...,-,-,0.0,0,0.0,0,NaN,-,14-09-2023 13:19,https://archives.nseindia.com/corporate/xbrl/I...
3,WESTLIFE,WESTLIFE FOODWORLD LIMITED,7(2),Banwari Lal Jatia jointly with Ushadevi Jatia,Promoter Group,Equity Shares,1187,0.00,NaN,50.0,...,-,-,0.0,0,0.0,0,NaN,-,14-09-2023 13:19,https://archives.nseindia.com/corporate/xbrl/I...
4,TIRUPATI,Shree Tirupati Balajee FIBC Limited,7(2),Binod Kumar Agarwal,Promoters,Equity Shares,240628,2.37,NaN,876.0,...,-,-,0.0,0,0.0,0,NSE,-,14-09-2023 13:07,https://archives.nseindia.com/corporate/xbrl/I...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18237,MHLXMIRU,Mahalaxmi Rubtech Limited,7(2),Rohan Anand Parekh,Promoters,Equity Shares,245596,2.31,NaN,170664.0,...,-,-,0.0,0,0.0,0,NaN,-,14-09-2022 12:23,https://archives.nseindia.com/corporate/xbrl/I...
18238,MHLXMIRU,Mahalaxmi Rubtech Limited,7(2),Amita Anand Parekh,Promoters,Equity Shares,170664,1.61,NaN,170664.0,...,-,-,0.0,0,0.0,0,NaN,-,14-09-2022 12:23,https://archives.nseindia.com/corporate/xbrl/I...
18239,ECLERX,eClerx Services Limited,7(2),Eclerx Employee Welfare Trust,Other,Equity Shares,715679,2.12,NaN,1538.0,...,-,-,0.0,0,0.0,0,NSE,-,14-09-2022 11:28,https://archives.nseindia.com/corporate/xbrl/I...
18240,ECLERX,eClerx Services Limited,7(2),Eclerx Employee Welfare Trust,Other,Equity Shares,717217,2.12,NaN,2800.0,...,-,-,0.0,0,0.0,0,NSE,-,14-09-2022 11:28,https://archives.nseindia.com/corporate/xbrl/I...
18241,MBAPL,Madhya Bharat Agro Products Limited,7(2),Nirmala Realinfrastructure Private Limited,Promoter Group,Equity Shares,789224,3.61,NaN,2565.0,...,-,-,0.0,0,0.0,0,NSE,-,14-09-2022 10:41,https://archives.nseindia.com/corporate/xbrl/I...

In [6]:
z=df['COMPANY'].unique()

In [7]:
v={}
for i in range (len(z)):
    c=len(df.loc[df['COMPANY']==z[i]])
    v[z[i]]=c
v

{'Nalwa Sons Investments Limited': 6,
 'WESTLIFE FOODWORLD LIMITED': 2,
 'Shree Tirupati Balajee FIBC Limited': 14,
 'Computer Age Management Services Limited': 26,
 'Navin Fluorine International Limited': 15,
 'Mittal Life Style Limited': 43,
 'NGL Fine-Chem Limited': 14,
 'JSW Holdings Limited': 23,
 '360 ONE WAM LIMITED': 279,
 'eClerx Services Limited': 144,
 'Onward Technologies Limited': 41,
 'MphasiS Limited': 149,
 'Info Edge (India) Limited': 159,
 'JSW Steel Limited': 280,
 'Mahindra & Mahindra Limited': 319,
 'Niit Learning Systems Limited': 4,
 'Syngene International Limited': 104,
 'Suryoday Small Finance Bank Limited': 9,
 'FSN E Commerce Ventures Limited': 437,
 'NIIT Limited': 45,
 'Bombay Dyeing & Mfg Company Limited': 10,
 'ADF Foods Limited': 16,
 'Sejal Glass Limited': 6,
 'Emmbi Industries Limited': 6,
 'DLF Limited': 14,
 'Shrenik Limited': 93,
 'Mastek Limited': 88,
 'Safari Industries (India) Limited': 115,
 'Kotak Mahindra Bank Limited': 45,
 'C.E. Info Systems Limited': 88,
 'Indusind Bank Limited': 540,
 'Fusion Micro Finance Limited': 85,
 'Star Cement Limited': 109,
 'Asian Granito India Limited': 18,
 'Crest Ventures Limited': 22,
 'Stove Kraft Limited': 15,
 'Triveni Engineering & Industries Limited': 5,
 'Tejas Networks Limited': 59,
 'Larsen & Toubro Limited': 108,
 'Action Construction Equipment Limited': 4,
 'Jyoti Structures Limited': 6,
 'Isgec Heavy Engineering Limited': 1,
 'The India Cements Limited': 12,
 'Capri Global Capital Limited': 23,
 'Ajooni Biotech Limited': 40,
 'Aurobindo Pharma Limited': 20,
 'L&T Technology Services Limited': 77,
 'Apollo Hospitals Enterprise Limited': 9,
 'Firstsource Solutions Limited': 44,
 'Gravita India Limited': 76,
 'TD Power Systems Limited': 100,
 'GHCL Limited': 28,
 'GRP Limited': 73,
 'Shyam Century Ferrous Limited': 64,
 'Kalyan Jewellers India Limited': 17,
 'TruCap Finance Limited': 21,
 'Hindustan Foods Limited': 98,
 'Frog Cellsat Limited': 9,
 'Titan Company Limited': 6,
 'KPI Green Energy Limited': 14,
 'Bajaj Auto Limited': 185,
 'Jeena Sikho Lifecare Limited': 31,
 'Indo Amines Limited': 121,
 'Remus Pharmaceuticals Limited': 59,
 'Avalon Technologies Limited': 7,
 'Shree Digvijay Cement Co.Ltd': 214,
 'Healthcare Global Enterprises Limited': 61,
 'JSW Energy Limited': 97,
 'GNA Axles Limited': 24,
 'Mahindra Holidays & Resorts India Limited': 124,
 'CCL Products (India) Limited': 9,
 'PG Electroplast Limited': 6,
 'Dr. Lal Path Labs Ltd.': 150,
 'Avenue Supermarts Limited': 420,
 'Landmark Cars Limited': 77,
 'JK Cement Limited': 9,
 'Sapphire Foods India Limited': 111,
 'Som Distilleries & Breweries Limited': 62,
 'Biocon Limited': 90,
 'Advanced Enzyme Technologies Limited': 63,
 'Vascon Engineers Limited': 26,
 'Sun TV Network Limited': 5,
 'Agro Tech Foods Limited': 38,
 'LTIMindtree Limited': 81,
 'Thomas Cook  (India)  Limited': 18,
 'VIP Industries Limited': 30,
 'Teamlease Services Limited': 14,
 'Aditya Birla Capital Limited': 176,
 'Satia Industries Limited': 6,
 'Banswara Syntex Limited': 22,
 'AIA Engineering Limited': 32,
 'Oracle Financial Services Software Limited': 35,
 'Paisalo Digital Limited': 16,
 'Dhruv Consultancy Services Limited': 6,
 'Kuantum Papers Limited': 3,
 'Prakash Steelage Limited': 53,
 'HDFC Life Insurance Company Limited': 59,
 'Usha Martin Limited': 29,
 'ROUTE MOBILE LIMITED': 17,
 'Mangalam Cement Limited': 9,
 'Godrej Agrovet Limited': 29,
 'GATI Limited': 26,
 'Nippon Life India Asset Management Limited': 186,
 'Prataap Snacks Limited': 6,
 'Shoppers Stop Limited': 70,
 'Astral Limited': 14,
 'Campus Activewear Limited': 128,
 'Subex Limited': 41,
 'Salasar Exteriors And Contour Limited': 6,
 'Lloyds Metals And Energy Limited': 2,
 'JB Chemicals & Pharmaceuticals Limited': 132,
 'KPIT Technologies Limited': 156,
 'Monarch Networth Capital Limited': 33,
 'D B Realty Limited': 37,
 'Jindal Photo Limited': 1,
 'Welspun Corp Limited': 16,
 'Hinduja Global Solutions Limited': 19,
 'Inox Wind Limited': 14,
 'Bharat Wire Ropes Limited': 16,
 'HCL Technologies Limited': 75,
 'Infibeam Avenues Limited': 49,
 'Zensar Technologies Limited': 19,
 'NRB Industrial Bearings Limited': 17,
 'Intellect Design Arena Limited': 90,
 'SRG Housing Finance Limited': 2,
 'TVS Holdings Limited': 23,
 'Lincoln Pharmaceuticals Limited': 82,
 'Ujjivan Financial Services Limited': 7,
 'Wipro Limited': 300,
 'Gland Pharma Limited': 19,
 'Kirloskar Industries Limited': 39,
 'Kirloskar Oil Engines Limited': 13,
 'HDFC Asset Management Company Limited': 54,
 'Solara Active Pharma Sciences Limited': 19,
 'Genus Power Infrastructures Limited': 6,
 'Emami Limited': 113,
 'Greenpanel Industries Limited': 7,
 'Prince Pipes And Fittings Limited': 8,
 'Max India Limited': 2,
 'Madhya Bharat Agro Products Limited': 30,
 'Sbfc Finance Limited': 5,
 'Aksh Optifibre Limited': 8,
 'Trent Limited': 3,
 'Tatva Chintan Pharma Chem Limited': 5,
 'Arihant Capital Markets Limited': 11,
 'Orissa Bengal Carrier Limited': 6,
 'Coforge Limited': 59,
 "Dr. Reddy's Laboratories Limited": 29,
 "Divi's Laboratories Limited": 70,
 'OM INFRA LIMITED': 1,
 'Balrampur Chini Mills Limited': 2,
 'Jayshree Tea & Industries Limited': 5,
 'Choice International Limited': 15,
 'Adani Power Limited': 4,
 'Morarjee Textiles Limited': 11,
 'Emami Realty Limited': 1,
 'Orient Electric Limited': 82,
 'Pidilite Industries Limited': 61,
 'Natco Pharma Limited': 11,
 'GVP Infotech Limited': 5,
 'Jindal Saw Limited': 20,
 'Sportking India Limited': 19,
 'S H Kelkar and Company Limited': 16,
 'Silly Monks Entertainment Limited': 3,
 'Nakoda Group of Industries Limited': 8,
 'Aries Agro Limited': 2,
 'Steel Strips Wheels Limited': 73,
 'Minda Corporation Limited': 22,
 'Trigyn Technologies Limited': 13,
 'AU Small Finance Bank Limited': 191,
 'Suzlon Energy Limited': 5,
 'Jayant Agro Organics Limited': 10,
 'Go Fashion (India) Limited': 7,
 'Infosys Limited': 288,
 'Greaves Cotton Limited': 88,
 'BIRLASOFT LIMITED': 96,
 'Mangalore Chemicals & Fertilizers Limited': 28,
 'Hindustan Unilever Limited': 12,
 'Indoco Remedies Limited': 13,
 'Pokarna Limited': 14,
 'Centrum Capital Limited': 35,
 'Cool Caps Industries Limited': 14,
 'Gillanders Arbuthnot & Company Limited': 2,
 'Krishana Phoschem Limited': 29,
 'Cyient Limited': 12,
 'Ramky Infrastructure Limited': 10,
 'Triveni Turbine Limited': 5,
 'Starteck Finance Limited': 1,
 'Innovana Thinklabs Limited': 2,
 'The Motor & General Finance Limited': 17,
 'IDFC First Bank Limited': 29,
 'ICICI Lombard General Insurance Company Limited': 18,
 'Elecon Engineering Company Limited': 16,
 'Arman Financial Services Limited': 13,
 'Maan Aluminium Limited': 3,
 'Race Eco Chain Limited': 4,
 'Zuari Agro Chemicals Limited': 10,
 'Brooks Laboratories Limited': 5,
 'Hindcon Chemicals Limited': 9,
 'Pritika Engineering Components Limited': 3,
 'Orient Bell Limited': 79,
 'Mahickra Chemicals Limited': 163,
 'Wanbury Limited': 1,
 'Atul Auto Limited': 27,
 'Consolidated Finvest & Holdings Limited': 5,
 'Sonata Software Limited': 24,
 'Lokesh Machines Limited': 15,
 'Centum Electronics Limited': 36,
 'Patel Integrated Logistics Limited': 46,
 'The Peria Karamalai Tea & Produce Company Limited': 19,
 'Salzer Electronics Limited': 16,
 'SIS LIMITED': 7,
 'Sun Pharmaceutical Industries Limited': 38,
 'Shilpa Medicare Limited': 9,
 'D.B.Corp Limited': 14,
 'Royal Orchid Hotels Limited': 22,
 'IFCI Limited': 1,
 'NRB Bearing Limited': 53,
 'Rachana Infrastructure Limited': 9,
 'Uma Exports Limited': 2,
 'NCL Industries Limited': 72,
 'Integrated Personnel Services Limited': 3,
 'BLB Limited': 8,
 'Allied Digital Services Limited': 7,
 'Ganges Securities Limited': 2,
 'Yasho Industries Limited': 2,
 'Focus Lighting and Fixtures Limited': 6,
 'Kernex Microsystems (India) Limited': 19,
 'Jindal Stainless Limited': 11,
 'V-Mart Retail Limited': 2,
 'Mahindra & Mahindra Financial Services Limited': 81,
 'Jamna Auto Industries Limited': 6,
 'Nahar Poly Films Limited': 12,
 'Mahindra Lifespace Developers Limited': 28,
 'Religare Enterprises Limited': 152,
 'Berger Paints (I) Limited': 29,
 'Stel Holdings Limited': 66,
 'Steelcast Limited': 6,
 'Shera Energy Limited': 1,
 'Shalimar Paints Limited': 5,
 '3i Infotech Limited': 1,
 'Clean Science And Technology Limited': 46,
 'CIE Automotive India Limited': 57,
 'Veto Switchgears And Cables Limited': 8,
 'Rainbow Childrens Medicare Limited': 20,
 'Ashiana Housing Limited': 15,
 'S.J.S. Enterprises Limited': 2,
 'Praj Industries Limited': 9,
 'Godrej Properties Limited': 18,
 'Ajanta Pharma Limited': 41,
 'OnMobile Global Limited': 13,
 'Unichem Laboratories Limited': 27,
 'Man Infraconstruction Limited': 29,
 'Oricon Enterprises Limited': 4,
 'HFCL Limited': 12,
 'The Andhra Sugars Limited': 7,
 'D. P. Abhushan Limited': 15,
 'Redtape Limited': 4,
 'Linc Limited': 21,
 'Pennar Industries Limited': 27,
 'The Ugar Sugar Works Limited': 13,
 'Sarda Energy & Minerals Limited': 2,
 'Neuland Laboratories Limited': 3,
 'Tainwala Chemical and Plastic (I) Limited': 10,
 'Indiabulls Housing Finance Limited': 3,
 'Mahindra Logistics Limited': 12,
 'Alkyl Amines Chemicals Limited': 30,
 'Jio Financial Services Limited': 5,
 'MEP Infrastructure Developers Limited': 65,
 'PDS Limited': 14,
 'Jai Balaji Industries Limited': 10,
 'Asian Energy Services Limited': 17,
 'Sterling and Wilson Renewable Energy Limited': 33,
 'Dhani Services Limited': 5,
 'Nahar Spinning Mills Limited': 9,
 'Nitco Limited': 2,
 'Jash Engineering Limited': 18,
 'Reliance Industries Limited': 3,
 'Aurionpro Solutions Limited': 19,
 'Ghcl Textiles Limited': 12,
 'NAVA LIMITED': 10,
 'Mayur Uniquoters Ltd': 4,
 'Bajaj Electricals Limited': 77,
 'Marksans Pharma Limited': 11,
 'Emkay Taps and Cutting Tools Limited': 3,
 'Chambal Fertilizers & Chemicals Limited': 91,
 'Jindal Steel & Power Limited': 62,
 'Vimta Labs Limited': 9,
 'DMCC SPECIALITY CHEMICALS LIMITED': 5,
 'Rolex Rings Limited': 40,
 'Bajaj Consumer Care Limited': 1,
 'Power Mech Projects Limited': 16,
 'Gulshan Polyols Limited': 10,
 'ICRA Limited': 2,
 'Ethos Limited': 13,
 'Zydus Wellness Limited': 57,
 'Tata Steel Limited': 2,
 'Jubilant Foodworks Limited': 11,
 'Syrma Sgs Technology Limited': 2,
 'LGB Forge Limited': 2,
 'Sundaram Multi Pap Limited': 2,
 'GMM Pfaudler Limited': 6,
 'IDFC Limited': 15,
 'Eris Lifesciences Limited': 6,
 'Sobha Limited': 15,
 'SPL Industries Limited': 3,
 'Ideaforge Technology Limited': 2,
 'Globus Spirits Limited': 6,
 'Poly Medicure Limited': 2,
 'JM Financial Limited': 22,
 'Sarveshwar Foods Limited': 2,
 'CSL Finance Limited': 45,
 'Thyrocare Technologies Limited': 6,
 "Capacit'e Infraprojects Limited": 2,
 'Felix Industries Limited': 1,
 'Abans Holdings Limited': 2,
 'Almondz Global Securities Limited': 49,
 'Marathon Nextgen Realty Limited': 5,
 'Vasa Retail and Overseas Ltd': 5,
 'Sigachi Industries Limited': 10,
 'Suven Pharmaceuticals Limited': 2,
 'Global Education Limited': 11,
 'Refex Industries Limited': 5,
 'Goldiam International Limited': 3,
 'Dhanuka Agritech Limited': 11,
 'Arvind Limited': 3,
 'Mangalam Drugs And Organics Limited': 17,
 'Reliance Home Finance Limited': 11,
 'Alicon Castalloy Limited': 13,
 'Ganga Forging Limited': 23,
 'Grindwell Norton Limited': 2,
 'Shivalik Bimetal Controls Limited': 4,
 'Shekhawati Poly-Yarn Limited': 4,
 'Excel Industries Limited': 5,
 'Thirumalai Chemicals Limited': 23,
 'Marico Limited': 6,
 'Euro Panel Products Limited': 24,
 'Cigniti Technologies Limited': 17,
 'Cambridge Technology Enterprises Limited': 14,
 'United Spirits Limited': 1,
 'Coffee Day Enterprises Limited': 12,
 'LG Balakrishnan & Bros Limited': 26,
 'Deepak Nitrite Limited': 7,
 'HDFC Bank Limited': 548,
 'Sterlite Technologies Limited': 14,
 '5Paisa Capital Limited': 19,
 'Bajaj Finserv Limited': 44,
 'Sula Vineyards Limited': 17,
 'Shah Metacorp Limited': 2,
 'LT Foods Limited': 4,
 'STEEL EXCHANGE INDIA LIMITED': 14,
 'Rail Vikas Nigam Limited': 2,
 'Inox Wind Energy Limited': 1,
 'Alok Industries Limited': 1,
 'Hi-Tech Pipes Limited': 26,
 'A G Universal Limited': 5,
 'Vaxtex Cotfab Limited': 23,
 'Deccan Cements Limited': 6,
 'JSW Ispat Special Products Limited': 2,
 'Sasken Technologies Limited': 29,
 'Ultra Wiring Connectivity System Limited': 5,
 'Dodla Dairy Limited': 3,
 'Bcl Industries Limited': 3,
 'Bikaji Foods International Limited': 3,
 'Ramco Systems Limited': 5,
 'Sakthi Sugars Limited': 5,
 'Surani Steel Tubes Limited': 7,
 'Dalmia Bharat Limited': 1,
 'E2E Networks Limited': 9,
 'AVG Logistics Limited': 1,
 'T T Limited': 13,
 'Patanjali Foods Limited': 1,
 'Nureca Limited': 2,
 'Hathway Cable & Datacom Limited': 1,
 'AXISCADES Technologies Limited': 77,
 'Mold-Tek Packaging Limited': 2,
 'Lyka Labs Limited': 16,
 'Arvind Fashions Limited': 27,
 'TV Vision Limited': 1,
 'Ginni Filaments Limited': 7,
 'Prozone Realty Limited': 13,
 'Sarla Performance Fibers Limited': 4,
 'Zota Health Care LImited': 5,
 'Parag Milk Foods Limited': 44,
 'Prime Focus Limited': 8,
 'Gujarat Apollo Industries Limited': 4,
 'Soma Textiles & Industries Limited': 28,
 'Aki India Limited': 7,
 'Advani Hotels & Resorts (India) Limited': 1,
 'ION Exchange (India) Limited': 2,
 'Chaman Metallics Limited': 3,
 'Madhav Marbles and Granites Limited': 11,
 'Karma Energy Limited': 3,
 'Khandwala Securities Limited': 6,
 'Godfrey Phillips India Limited': 10,
 'Univastu India Limited': 4,
 'B. L. Kashyap and Sons Limited': 6,
 'Raymond Limited': 2,
 'Manappuram Finance Limited': 5,
 'Barak Valley Cements Limited': 2,
 'Marshall Machines Limited': 11,
 'Gallantt Ispat Limited': 18,
 'Manomay Tex India Limited': 45,
 'Karur Vysya Bank Limited': 11,
 'Sanginita Chemicals Limited': 15,
 'Kaveri Seed Company Limited': 20,
 'Ind-Swift Laboratories Limited': 9,
 'COSMO FIRST LIMITED': 44,
 'UNO Minda Limited': 140,
 'BF Utilities Limited': 1,
 'Easy Trip Planners Limited': 2,
 'Shradha Infraprojects Limited': 2,
 'Manaksia Coated Metals & Industries Limited': 2,
 'Mrs. Bectors Food Specialities Limited': 2,
 'WE WIN LIMITED': 6,
 'Dangee Dums Limited': 2,
 'IG Petrochemicals Limited': 7,
 'Mukand Limited': 47,
 'Punjab Chemicals & Crop Protection Limited': 5,
 '21st Century Management Services Limited': 10,
 'Praxis Home Retail Limited': 28,
 'Rane Engine Valve Limited': 4,
 'Sundaram Finance Limited': 14,
 'Hindustan Oil Exploration Company Limited': 6,
 'Tara Chand InfraLogistic Solutions Limited': 10,
 'Sundaram Finance Holdings Limited': 7,
 'Avonmore Capital & Management Services  Limited': 41,
 'MITCON Consultancy & Engineering Services Limited': 40,
 'Airo Lam limited': 4,
 'Tamilnad Mercantile Bank Limited': 33,
 'Navkar Corporation Limited': 15,
 'India Nippon Electricals Limited': 4,
 'Synergy Green Industries Limited': 11,
 'Jubilant Industries Limited': 1,
 'Kirloskar Pneumatic Company Limited': 7,
 'Jubilant Pharmova Limited': 25,
 'N R Agarwal Industries Limited': 11,
 'Sagar Cements Limited': 1,
 'Sunflag Iron And Steel Company Limited': 3,
 'Aegis Logistics Limited': 3,
 'Greenply Industries Limited': 9,
 'Cybertech Systems And Software Limited': 3,
 'Rico Auto Industries Limited': 3,
 'Bajaj Holdings & Investment Limited': 35,
 'A B Infrabuild Limited': 10,
 'Bajaj Finance Limited': 25,
 'Omaxe Limited': 14,
 'Brand Concepts Limited': 12,
 'Craftsman Automation Limited': 1,
 'SMS Lifesciences India Limited': 3,
 'Geekay Wires Limited': 8,
 'Mtar Technologies Limited': 25,
 'Xpro India Limited': 21,
 'Indian Hume Pipe Company Limited': 19,
 'Jubilant Ingrevia Limited': 19,
 'SMS Pharmaceuticals Limited': 2,
 'RSWM Limited': 22,
 'Orbit Exports Limited': 3,
 'Digicontent Limited': 5,
 'Magnum Ventures Limited': 31,
 'Hisar Metal Industries Limited': 3,
 'Supreme Petrochem Limited': 14,
 'Globe Textiles (India) Limited': 31,
 'Homesfy Realty Limited': 1,
 'Lotus Eye Hospital and Institute Limited': 2,
 'India Motor Parts and Accessories Limited': 1,
 'Poonawalla Fincorp Limited': 26,
 'Iris Business Services Limited': 1,
 'KDDL Limited': 17,
 'Bliss GVS Pharma Limited': 4,
 'Syncom Formulations (India) Limited': 2,
 'Kriti Nutrients Limited': 4,
 'Fourth Dimension Solutions Limited': 35,
 'NHPC Limited': 2,
 'Motilal Oswal Financial Services Limited': 24,
 'Sikko Industries Limited': 4,
 'Premier Explosives Limited': 8,
 'Walpar Nutritions Limited': 3,
 'Indo Count Industries Limited': 2,
 'Pricol Limited': 12,
 'Power & Instrumentation (Gujarat) Limited': 4,
 'Chaman Lal Setia Exports Limited': 1,
 'Ortin Laboratories Limited': 12,
 'Apar Industries Limited': 3,
 'Servotech Power Systems Limited': 12,
 'Transwind Infrastructures Limited': 1,
 'Edelweiss Financial Services Limited': 8,
 'Paramount Communications Limited': 2,
 'Astec LifeSciences Limited': 1,
 'Atam Valves Limited': 2,
 'V-Guard Industries Limited': 108,
 'IRB Infrastructure Developers Limited': 2,
 'Nucleus Software Exports Limited': 1,
 'Hindprakash Industries Limited': 5,
 'Adani Ports and Special Economic Zone Limited': 4,
 'Sangam (India) Limited': 21,
 'Reliance Communications Limited': 2,
 'W S Industries (I) Limited': 14,
 'Proventus Agrocom Limited': 2,
 'Epigral Limited': 15,
 'Kopran Limited': 6,
 'Max Financial Services Limited': 35,
 'Affle (India) Limited': 2,
 'Speciality Restaurants Limited': 1,
 'Navneet Education Limited': 12,
 'The Hi-Tech Gears Limited': 4,
 'Zen Technologies Limited': 12,
 'Welspun Enterprises Limited': 1,
 'Laxmi Goldorna House Limited': 6,
 'PSP Projects Limited': 11,
 'Thomas Scott (India) Limited': 5,
 'GMR Airports Infrastructure Limited': 4,
 'Alembic Pharmaceuticals Limited': 8,
 'Meghmani Organics Limited': 8,
 'Time Technoplast Limited': 2,
 'The Anup Engineering Limited': 113,
 'Welspun India Limited': 31,
 'Manaksia Aluminium Company Limited': 11,
 'Imagicaaworld Entertainment Limited': 2,
 'Symphony Limited': 14,
 'Eicher Motors Limited': 4,
 'Dhampur Sugar Mills Limited': 18,
 'Dhampur Bio Organics Limited': 33,
 'Spectrum Electrical Industries Limited': 11,
 'Century Textiles & Industries Limited': 19,
 'Suumaya Industries Limited': 6,
 'Manugraph India Limited': 2,
 'Rushil Decor Limited': 6,
 'Nuvoco Vistas Corporation Limited': 2,
 'Ambani Organics Limited': 1,
 'Vedant Fashions Limited': 2,
 'Tanla Platforms Limited': 25,
 'Indo Borax & Chemicals Limited': 10,
 'Chemfab Alkalis Limited': 2,
 'GPT Infraprojects Limited': 7,
 'Hilton Metal Forging Limited': 7,
 'GI Engineering Solutions Limited': 2,
 'BLS International Services Limited': 32,
 'Arshiya Limited': 7,
 'Eimco Elecon (India) Limited': 9,
 'Repro India Limited': 10,
 'Shivalik Rasayan Limited': 6,
 'Nesco Limited': 1,
 'Rajratan Global Wire Limited': 7,
 'Kothari Sugars And Chemicals Limited': 1,
 'Genus Paper & Boards Limited': 2,
 'ITI Limited': 2,
 'Giriraj Civil Developers Limited': 6,
 'R Systems International Limited': 32,
 'Menon Bearings Limited': 1,
 'Lloyds Steels Industries Limited': 4,
 'Shaily Engineering Plastics Limited': 2,
 'Beardsell Limited': 2,
 'Shakti Pumps (India) Limited': 14,
 'Silver Touch Technologies Limited': 2,
 'GACM Technologies Limited': 2,
 'Stampede Capital Limited': 2,
 'Ramco Industries Limited': 18,
 'Ducon Infratechnologies Limited': 4,
 'Hubtown Limited': 4,
 'Mangalam Global Enterprise Limited': 7,
 'Cipla Limited': 5,
 'Hindustan Aeronautics Limited': 3,
 'Kabra Extrusion Technik Limited': 6,
 'Lasa Supergenerics Limited': 4,
 'Iris Clothings Limited': 5,
 'Mangalam Worldwide Limited': 9,
 'SecUR Credentials Limited': 9,
 'Kohinoor Foods Limited': 2,
 'Globesecure Technologies Limited': 3,
 'Compucom Software Limited': 1,
 'Confidence Petroleum India Limited': 12,
 'Asahi India Glass Limited': 9,
 'Nahar Industrial Enterprises Limited': 6,
 'RattanIndia Enterprises Limited': 4,
 'Panacea Biotec Limited': 8,
 'Metropolis Healthcare Limited': 4,
 'Future Consumer Limited': 3,
 'Kanpur Plastipack Limited': 8,
 'Usha Martin Education & Solutions Limited': 4,
 'Atlanta  Limited': 1,

In [8]:
df.groupby(['COMPANY']).count().sort_values('SYMBOL',ascending=False)

,SYMBOL,REGULATION,NAME_OF_THE_ACQUIRER/DISPOSER,CATEGORY_OF_PERSON,TYPE_OF_SECURITY_(PRIOR),NO._OF_SECURITY_(PRIOR),%_SHAREHOLDING_(PRIOR),TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED),NO._OF_SECURITIES_(ACQUIRED/DISPLOSED),VALUE_OF_SECURITY_(ACQUIRED/DISPLOSED),...,DERIVATIVE TYPE SECURITY \n,DERIVATIVE CONTRACT SPECIFICATION \n,NOTIONAL VALUE(BUY) \n,NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n,NOTIONAL VALUE(SELL) \n,NUMBER OF UNITS/CONTRACT LOT SIZE (SELL) \n,EXCHANGE \n,REMARK \n,BROADCASTE DATE AND TIME \n,XBRL \n
COMPANY,,,,,,,,,,,,,,,,,,,,,
HDFC Bank Limited,548,548,548,548,548,548,548,0,548,548,...,548,548,548,548,548,548,21,548,548,548
Indusind Bank Limited,540,540,540,540,540,540,540,0,540,540,...,540,540,540,540,540,540,302,540,540,540
FSN E Commerce Ventures Limited,437,437,437,437,437,437,437,0,437,437,...,437,437,437,437,437,437,246,437,437,437
Avenue Supermarts Limited,420,420,420,420,420,420,420,0,420,420,...,420,420,420,420,420,420,261,420,420,420
Mahindra & Mahindra Limited,319,319,319,319,310,319,319,0,310,319,...,319,319,319,319,319,319,94,319,319,319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Data Patterns (India) Limited,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,0,1,1,1
Sintercom India Limited,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,0,1,1,1
Dalmia Bharat Limited,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,0,1,1,1
DSJ Keep Learning Limited,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,0,1,1,1
20 Microns Limited,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,0,1,1,1

In [9]:
df.dtypes

SYMBOL                                           object
COMPANY                                          object
REGULATION                                       object
NAME_OF_THE_ACQUIRER/DISPOSER                    object
CATEGORY_OF_PERSON                               object
TYPE_OF_SECURITY_(PRIOR)                         object
NO._OF_SECURITY_(PRIOR)                          object
%_SHAREHOLDING_(PRIOR)                          float64
TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED)           float64
NO._OF_SECURITIES_(ACQUIRED/DISPLOSED)          float64
VALUE_OF_SECURITY_(ACQUIRED/DISPLOSED)           object
ACQUISITION/DISPOSAL_TRANSACTION_TYPE            object
TYPE_OF_SECURITY_(POST)                          object
NO._OF_SECURITY_(POST)                           object
%_POST                                           object
DATE_OF_ALLOTMENT/___ACQUISITION_FROM            object
Unnamed: 16                                      object
DATE OF ALLOTMENT/ ACQUISITION TO \n             object
DATE OF INITMATION TO COMPANY \n                 object
MODE OF ACQUISITION \n                           object
DERIVATIVE TYPE SECURITY \n                      object
DERIVATIVE CONTRACT SPECIFICATION \n             object
NOTIONAL VALUE(BUY) \n                          float64
NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n        int64
NOTIONAL VALUE(SELL) \n                         float64
NUMBER OF UNITS/CONTRACT LOT SIZE  (SELL) \n      int64
EXCHANGE \n                                      object
REMARK \n                                        object
BROADCASTE DATE AND TIME \n                      object
XBRL \n                                          object
dtype: object

In [10]:
df.describe()

,%_SHAREHOLDING_(PRIOR),TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED),NO._OF_SECURITIES_(ACQUIRED/DISPLOSED),NOTIONAL VALUE(BUY) \n,NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n,NOTIONAL VALUE(SELL) \n,NUMBER OF UNITS/CONTRACT LOT SIZE (SELL) \n
count,18242.000000,0.0,1.822200e+04,1.824200e+04,18242.000000,1.824200e+04,18242.000000
mean,4.994532,NaN,1.252391e+06,3.245428e+02,0.811315,3.252692e+02,0.811315
std,12.793022,NaN,2.964795e+07,1.872868e+04,34.624231,1.888827e+04,34.624231
min,0.000000,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,0.000000,NaN,1.875000e+03,0.000000e+00,0.000000,0.000000e+00,0.000000
50%,0.060000,NaN,8.346500e+03,0.000000e+00,0.000000,0.000000e+00,0.000000
75%,2.130000,NaN,5.000000e+04,0.000000e+00,0.000000,0.000000e+00,0.000000
max,99.990000,NaN,2.259335e+09,1.990900e+06,3000.000000,1.995000e+06,3000.000000

In [11]:
from datetime import datetime

date_string = "DATE_OF_ALLOTMENT/___ACQUISITION_FROM"

a= '%d-%b-%y' #specifify the format of the date_string.

date = pd.to_datetime(df[date_string], format=a,errors='coerce')
print(date)

0       2023-09-12
1       2023-09-12
2       2023-09-12
3       2023-09-12
4       2023-09-12
           ...
18237   2022-09-12
18238   2022-09-12
18239   2022-09-12
18240   2022-09-13
18241   2022-09-08
Name: DATE_OF_ALLOTMENT/___ACQUISITION_FROM, Length: 18242, dtype: datetime64[ns]

In [12]:
quarter_number = date.dt.quarter
df['quarter_number']=quarter_number

In [13]:
year_number=date.dt.year
df['year_number']=year_number

In [14]:
df.isna().sum()

SYMBOL                                              0
COMPANY                                             0
REGULATION                                          0
NAME_OF_THE_ACQUIRER/DISPOSER                       0
CATEGORY_OF_PERSON                                  0
TYPE_OF_SECURITY_(PRIOR)                           48
NO._OF_SECURITY_(PRIOR)                             0
%_SHAREHOLDING_(PRIOR)                              0
TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED)           18242
NO._OF_SECURITIES_(ACQUIRED/DISPLOSED)             20
VALUE_OF_SECURITY_(ACQUIRED/DISPLOSED)              0
ACQUISITION/DISPOSAL_TRANSACTION_TYPE               0
TYPE_OF_SECURITY_(POST)                             0
NO._OF_SECURITY_(POST)                              0
%_POST                                              0
DATE_OF_ALLOTMENT/___ACQUISITION_FROM               0
Unnamed: 16                                     18241
DATE OF ALLOTMENT/ ACQUISITION TO \n                0
DATE OF INITMATION TO COMPANY \n                    0
MODE OF ACQUISITION \n                              0
DERIVATIVE TYPE SECURITY \n                         0
DERIVATIVE CONTRACT SPECIFICATION \n                0
NOTIONAL VALUE(BUY) \n                              0
NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n          0
NOTIONAL VALUE(SELL) \n                             0
NUMBER OF UNITS/CONTRACT LOT SIZE  (SELL) \n        0
EXCHANGE \n                                      6519
REMARK \n                                           0
BROADCASTE DATE AND TIME \n                         0
XBRL \n                                             0
quarter_number                                     20
year_number                                        20
dtype: int64

In [15]:
df=df.loc[~df['year_number'].isna(),]

In [16]:
df.isna().sum()

SYMBOL                                              0
COMPANY                                             0
REGULATION                                          0
NAME_OF_THE_ACQUIRER/DISPOSER                       0
CATEGORY_OF_PERSON                                  0
TYPE_OF_SECURITY_(PRIOR)                           28
NO._OF_SECURITY_(PRIOR)                             0
%_SHAREHOLDING_(PRIOR)                              0
TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED)           18222
NO._OF_SECURITIES_(ACQUIRED/DISPLOSED)              0
VALUE_OF_SECURITY_(ACQUIRED/DISPLOSED)              0
ACQUISITION/DISPOSAL_TRANSACTION_TYPE               0
TYPE_OF_SECURITY_(POST)                             0
NO._OF_SECURITY_(POST)                              0
%_POST                                              0
DATE_OF_ALLOTMENT/___ACQUISITION_FROM               0
Unnamed: 16                                     18221
DATE OF ALLOTMENT/ ACQUISITION TO \n                0
DATE OF INITMATION TO COMPANY \n                    0
MODE OF ACQUISITION \n                              0
DERIVATIVE TYPE SECURITY \n                         0
DERIVATIVE CONTRACT SPECIFICATION \n                0
NOTIONAL VALUE(BUY) \n                              0
NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n          0
NOTIONAL VALUE(SELL) \n                             0
NUMBER OF UNITS/CONTRACT LOT SIZE  (SELL) \n        0
EXCHANGE \n                                      6519
REMARK \n                                           0
BROADCASTE DATE AND TIME \n                         0
XBRL \n                                             0
quarter_number                                      0
year_number                                         0
dtype: int64

In [17]:
df=df.loc[~df['year_number'].isna(),]

In [18]:
df.isna().sum()

SYMBOL                                              0
COMPANY                                             0
REGULATION                                          0
NAME_OF_THE_ACQUIRER/DISPOSER                       0
CATEGORY_OF_PERSON                                  0
TYPE_OF_SECURITY_(PRIOR)                           28
NO._OF_SECURITY_(PRIOR)                             0
%_SHAREHOLDING_(PRIOR)                              0
TYPE_OF_SECURITY_(ACQUIRED/DISPLOSED)           18222
NO._OF_SECURITIES_(ACQUIRED/DISPLOSED)              0
VALUE_OF_SECURITY_(ACQUIRED/DISPLOSED)              0
ACQUISITION/DISPOSAL_TRANSACTION_TYPE               0
TYPE_OF_SECURITY_(POST)                             0
NO._OF_SECURITY_(POST)                              0
%_POST                                              0
DATE_OF_ALLOTMENT/___ACQUISITION_FROM               0
Unnamed: 16                                     18221
DATE OF ALLOTMENT/ ACQUISITION TO \n                0
DATE OF INITMATION TO COMPANY \n                    0
MODE OF ACQUISITION \n                              0
DERIVATIVE TYPE SECURITY \n                         0
DERIVATIVE CONTRACT SPECIFICATION \n                0
NOTIONAL VALUE(BUY) \n                              0
NUMBER OF UNITS/CONTRACT LOT SIZE (BUY) \n          0
NOTIONAL VALUE(SELL) \n                             0
NUMBER OF UNITS/CONTRACT LOT SIZE  (SELL) \n        0
EXCHANGE \n                                      6519
REMARK \n                                           0
BROADCASTE DATE AND TIME \n                         0
XBRL \n                                             0
quarter_number                                      0
year_number                                         0
dtype: int64

In [19]:
df['year_quarter']=df['year_number'].astype('int').astype('str')+'-'+ df['quarter_number'].astype('int').astype('str')
#df['year_quarter_numeric']=df['year_per_quarter'].str.replace('-','').astype('int')

In [20]:
# Group by YEAR_QUARTER and COMPANY, and find the top 5 companies with max trading
top_5_companies = df.groupby(['year_quarter', 'COMPANY'])['SYMBOL'].count().reset_index()
sorted_df=top_5_companies.sort_values(by=['year_quarter','SYMBOL'],ascending=[True,False])
sorted_df.reset_index(drop=True,inplace=True)
sorted_df

     year_quarter                                   COMPANY  SYMBOL
0          2017-4                     Grand Foundry Limited       1
1          2019-4                     Grand Foundry Limited       1
2          2020-3                 Bajaj Electricals Limited       4
3          2020-3        Confidence Petroleum India Limited       1
4          2020-4                 Bajaj Electricals Limited       7
...           ...                                       ...     ...
2050       2023-3              The Ugar Sugar Works Limited       1
2051       2023-3                             Trent Limited       1
2052       2023-3  Ultra Wiring Connectivity System Limited       1
2053       2023-3                    United Spirits Limited       1
2054       2023-3                           Wanbury Limited       1

[2055 rows x 3 columns]

In [21]:
#top_5_companies = df.groupby(['year_quarter', 'COMPANY','ACQUISITION/DISPOSAL_TRANSACTION_TYPE'])['SYMBOL'].count().reset_index()
#top_5_companies

In [22]:
#top_5_companies.loc[df['COMPANY']==[],]
sorted_df.loc[sorted_df['COMPANY']=='HDFC Bank Limited',]

     year_quarter            COMPANY  SYMBOL
26         2022-3  HDFC Bank Limited      92
313        2022-4  HDFC Bank Limited     112
775        2023-1  HDFC Bank Limited      63
1263       2023-2  HDFC Bank Limited     214
1690       2023-3  HDFC Bank Limited      67

In [23]:
sorted_df=sorted_df.reset_index()
sorted_df

      index year_quarter                                   COMPANY  SYMBOL
0         0       2017-4                     Grand Foundry Limited       1
1         1       2019-4                     Grand Foundry Limited       1
2         2       2020-3                 Bajaj Electricals Limited       4
3         3       2020-3        Confidence Petroleum India Limited       1
4         4       2020-4                 Bajaj Electricals Limited       7
...     ...          ...                                       ...     ...
2050   2050       2023-3              The Ugar Sugar Works Limited       1
2051   2051       2023-3                             Trent Limited       1
2052   2052       2023-3  Ultra Wiring Connectivity System Limited       1
2053   2053       2023-3                    United Spirits Limited       1
2054   2054       2023-3                           Wanbury Limited       1

[2055 rows x 4 columns]

In [35]:
X.reshape(-1, 1)

array([[   0],
       [   1],
       [   2],
       ...,
       [2052],
       [2053],
       [2054]], dtype=int64)

In [36]:
from sklearn.linear_model import LinearRegression
X = sorted_df['index'].values
y = sorted_df['SYMBOL'].values
linear_model= LinearRegression()
linear_model.fit(X.reshape(-1, 1), y.reshape(-1, 1))

LinearRegression()

In [40]:
y=linear_model.predict(X.reshape(-1, 1))
y

array([[10.16834474],
       [10.16707776],
       [10.16581078],
       ...,
       [ 7.56849579],
       [ 7.56722881],
       [ 7.56596183]])